encyclopedia/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index1, name="index1"),
    path("wiki/", views.index, name="index"),
    path("wiki/<str:q>", views.search, name="search"),
    path("wiki/edit/", views.edit, name="edit"),
    path("wiki/update/", views.update, name="update"),
    path("wiki/createPage/", views.createPage, name="createPage"),
    path("wiki/random/", views.randomPage, name="randomPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from . import util
import markdown2
import random


# This is a new render function
class searchForm(forms.Form):
    q = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'placeholder': 'Search Encyclopedia'
    }))


# This create a form object
class newPageForm(forms.Form):
    title = forms.CharField(label="Title", max_length=100,
                            widget=forms.TextInput(attrs={
                                'placeholder': 'Enter your Title here'
                            }))
    content = forms.CharField(
        label="Content",
        widget=forms.Textarea(attrs={
            'placeholder': 'Enter your MD text here'
        }
        ))


# This return the original Content title
def check(title):
    for i in util.list_entries():
        if title.lower() == i.lower():
            return i


# If the User vist direct website not "wiki/"
def index1(request):
    return HttpResponseRedirect(reverse("index"))


# This is the Main Page of the website
def index(request, methods=["GET", "POST"]):
    if request.method == "POST":
        form = searchForm(request.POST)
        if form.is_valid():
            q = form.cleaned_data["q"]
            return search(request, q)
    else:
        if "pageCreated" not in request.session:
            request.session['pageCreated'] = False
            pageCreated = False
        elif request.session.get('pageCreated') == True:
            pageCreated = True
            request.session['pageCreated'] = False
        else:
            pageCreated = False
        if "newpage" not in request.session:
            request.session["newpage"] = False
        if "message" not in request.session:
            request.session["message"] = None
        return render(request, "encyclopedia/index.html", {
            "pageCreated": pageCreated,
            "newPage": request.session["newpage"],
            "message": request.session["message"],
            "searchForm": searchForm(),
            "entries": util.list_entries()
        })


# This gives list of suggested seraches
def suggest(request, q):
    s = []
    for i in util.list_entries():
        if q.casefold() in i.casefold():
            s.append(i)
    return s


# This is the search result page of the website
def search(request, q=None):
    if q and q != '':
        content = util.get_entry(q)
        s = suggest(request, q)
        if content:
            return render(request, "encyclopedia/search.html", {
                "searchForm": searchForm(),
                "title": check(q),
                "content": markdown2.markdown(content)
            })
        elif s:
            return render(request, "encyclopedia/suggestions.html", {
                "searchForm": searchForm(),
                "q": q,
                "nResult": len(s),
                "entries": s
            })
        else:
            return render(request, "encyclopedia/404.html", {
                "searchForm": searchForm(),
            })
    else:
        return HttpResponseRedirect(reverse("index"))


# This render to the existing page
def edit(request, method=["POST"]):
    t = request.POST["title"]
    form = newPageForm(initial={
        "title": check(t),
        "content": util.get_entry(t)
    })
    return render(request, "encyclopedia/edit.html", {
        "searchForm": searchForm(),
        "title": check(t),
        "form": form
    })


# This updates the server data
def update(request, method=["POST"]):
    return createPage(request, update=True)


# This Creates a new wiki Page
def createPage(request, methods=["GET", "POST"], update=False):
    if request.method == "POST":
        form = newPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if not util.get_entry(title) or update:
                util.save_entry(title, content)
                request.session["pageCreated"] = True
                request.session["newpage"] = title
                if update:
                    request.session["message"] = "updated"
                else:
                    request.session["message"] = "created"
                return HttpResponseRedirect(reverse("index"))
            else:
                return render(request, "encyclopedia/createPage.html", {
                    "searchForm": searchForm(),
                    "titleError": True,
                    "title": title,
                    "form": form
                })
        else:
            return render(request, "encyclopedia/404.html")
    else:
        return render(request, "encyclopedia/createPage.html", {
            "searchForm": searchForm(),
            "titleError": False,
            "form": newPageForm()
        })


# This is render to a random page
def randomPage(request):
    r = random.choice(util.list_entries())
    return search(request, r)

encyclopedia/templates/encyclopedia/createPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create a new Page - Encyclopedia
{% endblock %}

{% block body %}

<!-- This is the Notification of title already exist -->
{% if titleError %}
<style>
    #titleError {
        display: block;
    }

    #titleError2 {
        display: block;
    }
</style>
{% else %}
<style>
    #titleError {
        display: none;
    }

    #titleError2 {
        display: none;
    }
</style>
{% endif %}


<div id="titleError" class="alert alert-danger alert-dismissible fade show" role="alert">
    A Wiki Page of name "<strong>{{ title }}</strong>" already exist.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div id="titleError2" class="alert alert-warning alert-dismissible fade show" role="alert">
    Try adding another content or edit the existing page at <a
        href="{% url 'index' %}{{ title }}">{% url 'index' %}{{ title }}</a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<!-- This is the form to create a new wiki page -->
<h1 style="display: inline-flex;">Create a New <p style="padding: 0em 0.3em;" class="text-primary mb-0"> Wiki </p> Page
</h1>
<hr class="mt-0 mb-2">
<form action="{% url 'createPage' %}" method="POST">
    {% csrf_token %}

    {% for item in form %}
    {{ item.label }} <br>
    {{ item }}<br>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="Create Page">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit Page - Encyclopedia
{% endblock %}

{% block body %}
<!-- This is the edit page form -->
<h1 style="display: inline-flex;">Edit<p style="padding: 0em 0.3em;" class="text-primary mb-0">{{ title }}</p> Page
</h1>
<hr class="mt-0 mb-2">
<form action="{% url 'update' %}" method="POST">
    {% csrf_token %}

    {% for item in form %}
    {% if "itle" in item.label %}
    <div style="display: none;">
        {{ item.label }} <br>
        {{ item }}<br>
    </div>
    {% else %}
    {{ item.label }} <br>
    {{ item }}<br>
    {% endif %}
    {% endfor %}

    <input type="submit" class="btn btn-primary" value="Save Changes">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

<!-- This is the notification for new page created -->
{% if pageCreated == True %}
<style>
    #page_Created {
        display: block !important;
    }
</style>
{% else %}
<style>
    #page_Created {
        display: none !important;
    }
</style>
{% endif %}

<div id="page_Created" class="alert alert-success" role="alert">
    <h4 class="alert-heading">Well done!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </h4>
    <p><strong>{{ newPage }}</strong> page is successfully {{ message }}.</p>
    <hr>
    <p class="mb-0">You may visit at <a href="{% url 'index' %}{{ newPage }}">{% url 'index' %}{{ newPage }}</a>.</p>
</div>

<!-- This a the main index/home page -->
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li><a href="{% url 'index' %}{{ entry }}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- These are some helpful links -->
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    <link href="{% static 'encyclopedia/favicon.svg' %}" rel="shortcut icon">
    <style>
        /* This hides the q: above serach box */
        label[for="id_q"] {
            display: none;
        }
    </style>
</head>

<body style="min-width: 300px;">
    <div class="row" style="margin: 0px !important;">
        <div class="sidebar col-lg-2 col-md-3">

            <a id="brandText" href="{% url 'index' %}">
                <center>
                    <!-- This is the brand logo -->
                    <img style="max-width: -webkit-fill-available;" src="{% static 'encyclopedia/brand-logo.png' %}"
                        alt="Wikipedia">

                    <h2>Wiki</h2>
                </center>
            </a>

            <!-- This is the search box -->
            <form action="{% url 'index' %}" method="post">
                {% csrf_token %}
                {{ searchForm }}
                <style>
                    #id_q {
                        padding: 2px 10px;
                        border: 2px solid #343a40;
                        margin-bottom: 10px;
                    }

                    #id_q:hover,
                    #id_q:focus,
                    #id_q:active {
                        outline: 0px;
                        border: 2px solid #007bff;
                    }
                </style>
            </form>

            <!-- These are some helpful links -->
            <div>
                <a href="{% url 'index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'createPage' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'randomPage' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main shadow col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>


    <!-- This is the js of bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }} - Encyclopedia
{% endblock %}

{% block body %}

<!-- This is the result content of the wiki page -->
{% autoescape off %}{{ content }}{% endautoescape %}

<!-- This is the Edit page button -->
<form action="{% url 'edit' %}" method="POST">
    {% csrf_token %}
    <input style="display: none;" name="title" type="text" value="{{ title }}">
    <input type="submit" value="Edit" class="btn btn-outline-secondary">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/suggestions.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ q }} - Encyclopedia
{% endblock %}

{% block body %}
<!-- This is the template for suggestion related to the word searched -->
<h1 style="display: inline-flex;">Suggestions for "<p class="text-primary mb-0">{{ q }}</p>"</h1>
<hr class="mt-0 mb-2">
<h6>Found {{ nResult }} result{% if nResult > 1 %}s{% endif %}</h6>
<ul>
    {% for entry in entries %}
    <li><a href="{% url 'index' %}{{ entry }}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}